### ISSUE TITLE
Errors occur when removing the environment

### ISSUE THREAD

**Issue by mmarchetti** [Anaconda-Server/nbsetuptools#2]
If you `conda create -n testenv anaconda-notebook` then `conda env remove -n testenv`, you will get an error from the post-link script in the extensions that use nbsetuptools:

```
Unlinking packages ...
[mistune             ]|#############Traceback (most recent call last):########                                                                                                                      |  32%
  File "/Users/mmarchetti/anaconda/envs/nbtest/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/mmarchetti/anaconda/envs/nbtest/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/mmarchetti/anaconda/envs/nbtest/lib/python2.7/site-packages/nb_conda/setup.py", line 1, in <module>
    from nbsetuptools import setup, find_static
  File "/Users/mmarchetti/anaconda/envs/nbtest/lib/python2.7/site-packages/nbsetuptools/__init__.py", line 1, in <module>
    from .nbsetuptools import setup, find_static
  File "/Users/mmarchetti/anaconda/envs/nbtest/lib/python2.7/site-packages/nbsetuptools/nbsetuptools.py", line 12, in <module>
    from funcsigs import signature
ImportError: No module named funcsigs
```

Has conda already unlinked funcsigs from the environment?

**Comment by mmarchetti** [comment]
Today I saw a similar issue:

```
  Unlinking packages ...
  [libpng              ]|#############Traceback (most recent call last):                                                                                                                              |  27%
  File "/Users/mmarchetti/anaconda/envs/nb/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/mmarchetti/anaconda/envs/nb/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/mmarchetti/anaconda/envs/nb/lib/python3.5/site-packages/nb_conda/setup.py", line 1, in <module>
    from nbsetuptools import setup, find_static
  File "/Users/mmarchetti/anaconda/envs/nb/lib/python3.5/site-packages/nbsetuptools/__init__.py", line 1, in <module>
    from .nbsetuptools import setup, find_static
  File "/Users/mmarchetti/anaconda/envs/nb/lib/python3.5/site-packages/nbsetuptools/nbsetuptools.py", line 13, in <module>
    from jupyter_core.paths import jupyter_config_dir
  ImportError: No module named 'jupyter_core'
```
